version: '3'

services:
  router1:
    hostname: router1
    environment:
      - CLIENT_LISTEN_PORT=5555
      - COUNTERPARTY_LISTEN_PORT=6666
      - COUNTERPARTY_HOST=router2 # Use service name instead of IP address
      - COUNTERPARTY_HOST_PORT=6666
    build: ../Router

  router2:
    hostname: router2
    environment:
      - CLIENT_LISTEN_PORT=5555
      - COUNTERPARTY_LISTEN_PORT=6666
      - COUNTERPARTY_HOST=router1 # Use service name instead of IP address
      - COUNTERPARTY_HOST_PORT=6666
    build: ../Router

  p01a:
    hostname: p01a
    environment:
      - ROUTER_HOSTNAME=router1 # Use service name instead of IP address
      - FILE_NAME=/app/manhattan_soviet_map_2048.jpg
      - TARGET_NAME=p01b,p02b
    build: ../Peer
    volumes:
      - type: bind
        source: ./test-files/JPG/manhattan_soviet_map_2048.jpg
        target: /app/manhattan_soviet_map_2048.jpg
    depends_on:
      - router1
      - router2

  p01b:
    hostname: p01b
    environment:
      - ROUTER_HOSTNAME=router2 # Use service name instead of IP address
    build: ../Peer
    volumes:
      - type: volume
        source: p01b
        target: /app
    depends_on:
      - router1
      - router2

  p02b:
    hostname: p02b
    environment:
      - ROUTER_HOSTNAME=router2 # Use service name instead of IP address
    build: ../Peer
    volumes:
      - type: volume
        source: p02b
        target: /app
    depends_on:
      - router1
      - router2

volumes:
  p01b:
  p02b:
