version: '3'
networks:
  pdc-net: # Docker-only overlay network
    ipam:
      config:
        - subnet: 172.23.0.0/16

services:
  router1:
    hostname: router1
    environment:
      - CLIENT_LISTEN_PORT=5555
      - COUNTERPARTY_LISTEN_PORT=6666
      - COUNTERPARTY_HOST=172.23.0.6
      - COUNTERPARTY_HOST_PORT=6666
    build: ../Router
    networks:
      pdc-net:
         ipv4_address: 172.23.0.5
  router2:
    hostname: router2
    environment:
      - CLIENT_LISTEN_PORT=5555
      - COUNTERPARTY_LISTEN_PORT=6666
      - COUNTERPARTY_HOST=172.23.0.5
      - COUNTERPARTY_HOST_PORT=6666
    build: ../Router
    networks:
      pdc-net:
         ipv4_address: 172.23.0.6
  p01a:
    hostname: p01a
    environment:
      - ROUTER_HOSTNAME=172.23.0.5
      - FILE_NAME=/app/manhattan_soviet_map_2048.jpg
      - TARGET_NAME=p01b
    build: ../Peer
    volumes:
      - type: bind
        source: ./test-files/JPG/manhattan_soviet_map_2048.jpg
        target: /app/manhattan_soviet_map_2048.jpg
    networks:
      - pdc-net
    depends_on:
      - router1
      - router2


  p01b:
    hostname: p01b
    environment:
      - ROUTER_HOSTNAME=172.23.0.6
    build: ../Peer
    volumes:
      - type: volume
        source: p01b
        target: /app
    networks:
      - pdc-net
    depends_on:
      - router1
      - router2

volumes:
  p01b:
