version: '3'
networks:
  pdc-net: # Docker-only overlay network
    ipam:
      config:
        - subnet: 172.23.0.0/16

services:
  router1:
    container_name: router1
    environment:
      - CLIENT_LISTEN_PORT=5555
      - COUNTERPARTY_LISTEN_PORT=6666
      - COUNTERPARTY_HOST=172.23.0.6
      - COUNTERPARTY_HOST_PORT=6666
    build: ../Router
    networks:
      pdc-net:
         ipv4_address: 172.23.0.5
  router2:
    container_name: router2
    environment:
      - CLIENT_LISTEN_PORT=5555
      - COUNTERPARTY_LISTEN_PORT=6666
      - COUNTERPARTY_HOST=172.23.0.5
      - COUNTERPARTY_HOST_PORT=6666
    build: ../Router
    networks:
      pdc-net:
         ipv4_address: 172.23.0.6
  p01a:
    container_name: p01a
    environment:
      - ROUTER_HOSTNAME=router1
      - FILE_NAME='shia_surprise_94_kbps_240p.mp4'
      - TARGET_NAME=p01b
    build: ../Peer
    volumes:
      - type: bind
        source: ./test-files/MP4/shia_surprise_94_kbps_240p.mp4
        target: /app/shia_surprise_94_kbps_240p.mp4

  p01b:
    container_name: p01b
    environment:
      - ROUTER_HOSTNAME=router2
    build: ../Peer
    volumes:
      - type: volume
        source: p01b
        target: /app

volumes:
  p01b:
